<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Analisis Web</title>
    <style>
        /* CSS Klasik untuk DomPDF */
        body { font-family: sans-serif; color: #333; font-size: 14px; }
        .header { text-align: center; border-bottom: 2px solid #0d6efd; padding-bottom: 10px; margin-bottom: 20px; }
        .header h2 { margin: 0; color: #0d6efd; }
        .header p { margin: 5px 0 0 0; font-size: 12px; color: #666; }
        
        .section-title { font-size: 16px; font-weight: bold; margin-bottom: 10px; margin-top: 20px; border-bottom: 1px solid #ccc; padding-bottom: 5px;}
        
        /* Menggunakan tabel untuk layout yang kokoh di PDF */
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        table th, table td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        table th { background-color: #f8f9fa; width: 35%; }
        
        .text-success { color: #198754; font-weight: bold; }
        .text-warning { color: #ffc107; font-weight: bold; }
        .text-danger { color: #dc3545; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; font-size: 11px; color: #999; border-top: 1px solid #ddd; padding-top: 10px;}
    </style>
</head>
<body>

    <div class="header">
        <h2>Laporan Analisis Website</h2>
        <p>Generated by Web Analyzer Tool</p>
    </div>

    <table>
        <tr>
            <th>URL Target</th>
            <td><strong>{{ $report->url }}</strong></td>
        </tr>
        <tr>
            <th>Waktu Analisis</th>
            <td>{{ $report->created_at->format('d F Y, H:i:s') }}</td>
        </tr>
    </table>

    <div class="section-title">1. Hasil Analisis Google PageSpeed</div>
    <table>
        <tr>
            <th>Skor Performa</th>
            <td>
                <span class="{{ $report->performance_score >= 80 ? 'text-success' : ($report->performance_score >= 50 ? 'text-warning' : 'text-danger') }}">
                    {{ $report->performance_score ?? 'N/A' }} / 100
                </span>
            </td>
        </tr>
        <tr>
            <th>Skor SEO</th>
            <td>
                <span class="{{ $report->seo_score >= 80 ? 'text-success' : ($report->seo_score >= 50 ? 'text-warning' : 'text-danger') }}">
                    {{ $report->seo_score ?? 'N/A' }} / 100
                </span>
            </td>
        </tr>
    </table>

    <div class="section-title">2. Hasil Pengecekan Keamanan (VirusTotal)</div>
    <table>
        <tr>
            <th>Status Keamanan</th>
            <td>
                <span class="{{ $report->security_status == 'Safe/Aman' ? 'text-success' : 'text-danger' }}">
                    {{ $report->security_status ?? 'N/A' }}
                </span>
            </td>
        </tr>
        <tr>
            <th>Deteksi Malware / Phising</th>
            <td>
                @if($report->malicious_votes > 0)
                    <span class="text-danger">Terdeteksi bahaya oleh {{ $report->malicious_votes }} vendor!</span>
                @else
                    <span class="text-success">Bersih (0 deteksi)</span>
                @endif
            </td>
        </tr>
    </table>

    <div class="footer">
        Dokumen ini di-generate secara otomatis pada {{ date('d F Y') }}.<br>
        Web Analyzer Tool &copy; {{ date('Y') }}
    </div>

</body>
</html>